### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by sina-mansour** [niivue/ipyniivue#1]
I just noticed this git repository and was wondering if this has yet started? I think this could be a great addition to jupyter for neuroimaging analyses.

I was wondering if there are any plans to make this a reality?

**Comment by hanayik** [comment]
Hi @sina-mansour, 

Yes! there are plans. We have focussed our efforts so far on the core NiiVue project (the visualisation library). We are now switching gears to the NiiVue-UI (user interface) project for the OHBM hackathon. We have someone on the team that would like to work on the Jupyter notebook as a senior thesis project starting in the Fall (August or September). However, we can definitely start sooner than that if there is some demand. 

Do you have experience writing Jupyter notebook extensions?

**Comment by sina-mansour** [comment]
Hi @hanayik,

I have previously used Jupyter notebook extensions, but haven't developed one before. I'm happy to look into it and see if I'm able to do much though.

In fact, recently, I've been searching for an all-purpose visualization toolkit for 3d rendering in python. I came across tools such as Mayavi which I'm currently using mostly, but it's not well integrated with Jupyter or webGL and such features don't seem to be currently under development for Mayavi.

I came across the NiiVue project during the OHBM brainhack and looking into the demos I felt that NiiVue actually is capable of visualizing various 3d formats and thought it would be really cool to have it integrated with Jupyter for interactive visualizations.

Essentially, since Jupyter should theoretically be capable of visualizing HTML, it would be possible to integrate the NiiVue visualization within it. I know that tools such as [k3d-jupyter](https://github.com/K3D-tools/K3D-jupyter) accomplish this with webGL in Jupyter.

**Comment by hanayik** [comment]
@sina-mansour , Thanks for your reply, and apologies for the delayed response. @AnthonyAndroulakis is working on the Jupyter extension and we hope to make some significant progress over the next few months. I would definitely recommend checking back periodically. And please submit any feedback if you start using the extension (once it's more widely available)
