### ISSUE TITLE
2 columns of turquoise showing around widget

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/ipyniivue#11]
**Describe the bug**
When a Niivue widget is created, 2 columns of turquoise can be seen on the left and right sides.

**To Reproduce**
1. Install ipyniivue using the [installation steps](https://github.com/niivue/ipyniivue#installation). If needed, install yarn using `npm install -g yarn`
2. Open jupyter lab using `jupyter lab`
3. Open the examples -> introduction.ipynb file
4. Run the first two code sections.
5. See the strips of turquoise on the left and right sides of the Niivue widget.

**Expected behavior**
No turquoise should be visible unless the background color is set to turquoise. Since the default background color is black, the background should just consist of black.

**Screenshots**
Current display. The arrows at the bottom point to the thin strips of turquoise.
<img width="813" alt="Screen Shot 2022-10-18 at 11 14 33 AM" src="https://user-images.githubusercontent.com/43938491/196471371-8a03df39-fb00-4103-a1f6-26bb356bba43.png">

**Comment by hanayik** [comment]
@AnthonyAndroulakis , is that just the "focus" ring around the canvas since the canvas has focus when it is attached to a niivue instance?

**Comment by AnthonyAndroulakis** [comment]
hm, I didn't know about canvas focus rings. It could be case. This is probably not a bug then, right?
