### ISSUE TITLE
Embed ipyniivue in exported document

### ISSUE THREAD

**Issue by alexisthual** [niivue/ipyniivue#14]
I just tried exporting a jupyter notebook comprising a cell generated with ipyniivue. I exported it as an html file in order to see what kind of information would be embedded in the document.

In place of the output of the widget, there is a textual description of the widget. This was what I expected would happen, but I'd be interested to hear if you have plans for users to export static HTML files in the future!

Thank you for the nice library anyways! :blush: 

Jupyter notebook
![Screenshot from 2022-12-08 20-27-51](https://user-images.githubusercontent.com/13835654/206549428-56ace552-030a-48ce-9e9f-abbc082a99b7.png)

Exported HTML file
![Screenshot from 2022-12-08 20-26-36](https://user-images.githubusercontent.com/13835654/206549436-0bd9b22e-a608-4857-998c-45513660f719.png)

**Comment by AnthonyAndroulakis** [comment]
This would be useful. We should look into this.

**Comment by AnthonyAndroulakis** [comment]
Some notes from the nilearn dev team meeting:
- load object/volume/mesh into niivue -> turn into array base64 string and save into notebook
- output should be self-contained
- NiivueModel should store the array of base64 strings (and other data about model state)
- when a new cell is run (ie NiivueView rendered), an update() function should be called that reads the array of base64 strings and displays the niivue instance
