### ISSUE TITLE
Argument of set_volume not being taken into account.

### ISSUE THREAD

**Issue by christian-oreilly** [niivue/ipyniivue#18]
The path of the volume passed to the `Niivue.set_volume` seems to have no effect. For example:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/5932954/212496308-216afc0b-9e3f-46f3-9f21-ee90982f7168.png">

As expected, I suppose, for this example from the doc. But now look at this example:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/5932954/212496365-5e26de3d-2678-45a5-993d-8509121c6eb0.png">

**Comment by AnthonyAndroulakis** [comment]
Interesting. I'll test this out today and get back to you. Also, set_volume is a temporary function (currently used for testing on_change callbacks).

**Comment by christian-oreilly** [comment]
Thanks for the feedback. If it is intended as a temporary function, what is the function that is expected in long run to be used to load the data that we want to work with?

**Comment by AnthonyAndroulakis** [comment]
add_volume_from_url would be the most similar function:
```py
import ipyniivue
nv = ipyniivue.Niivue()
nv.add_volume_from_url("https://niivue.github.io/niivue/images/mni152.nii.gz")
```

**Comment by christian-oreilly** [comment]
That is fine, but most neuroimaging work is not done on the web but on local computer (or on the local file system of a cluster). I'd personally consider loading a volume from a local system an "essential feature" and loading a file from a URL only a "nice to have" feature.

**Comment by hanayik** [comment]
@AnthonyAndroulakis and @christian-oreilly , `add_volume_from_url` should also be able to load a volume from the users's file system. 

For example, you can see how I do it [here](https://github.com/niivue/niivue-desktop/blob/main/src/fileServer.js#L17) using a local nodejs server in the niivue desktop app. I thought that we could do something similar in python. You can see how AFNI do this using Flask in python [here](https://github.com/afni/afni/pull/380/files#diff-61c2538494e57477685ac0ddde154277e178a7f30f6d4afc80791942202ce584R257)

**Comment by AnthonyAndroulakis** [comment]
Sounds good. I'll look into it. It might be possible to just read the data and pass that data into Niivue? 
Since it's a planned feature to be able to load in an image from data or nibabel.Nifti1Image object (see [https://github.com/nilearn/nilearn/issues/3451](nilearn), it might be good for me to add in a way to read the data from the file.

**Comment by AnthonyAndroulakis** [comment]
I agree that the `set_volume` function can just be a thin layer of abstraction that uses add_volume_from_url. 

Instead of hosting files on a server perhaps we can use [NVImage.loadFromBase64](https://github.com/niivue/niivue/blob/main/src/nvimage.js#L2880)?

**Comment by AnthonyAndroulakis** [comment]
I replaced the set_volume function with an add_volume function. This function takes in 1 input: the location of the file. This can either be a url or a local file.
Examples:
```py
import ipyniivue
w = ipyniivue.Niivue(crosshair_color=[0,1,0,1])
w.add_volume('https://niivue.github.io/niivue/images/mni152.nii.gz')
display(w)
```
```py
import ipyniivue
w = ipyniivue.Niivue(crosshair_color=[0,1,0,1])
w.add_volume('/Users/anthony/Downloads/CT_pitch.nii.gz')
display(w)
```

This add_volume function also accepts file urls, like `file:///Users/anthony/Downloads/CT_pitch.nii.gz`

**Comment by AnthonyAndroulakis** [comment]
closing as solved
