### ISSUE TITLE
Testing for examples

### ISSUE THREAD

**Issue by christian-oreilly** [niivue/ipyniivue#22]
I have been working on documenting a bit better the Google Colab examples and adding at least one new. In doing so, it came to mind that these need to be part of the CI tests so that updates breaking these are flagged by the CI and blocked from merging.  These notebooks can be automatically converted in Python script easily with:

`jupyter nbconvert --to script [YOUR_NOTEBOOK].ipynb`

I guess that these could be then integrated in `pytest` with something like (untested):

```python
from pathlib import Path
import runpy

def test_notebooks():
    notebooks = Path([PATH_TO_NOTEBOOKS]).glob("*.ipynb")
    for notebook in notebooks:
        command = f'jupyter nbconvert --to script {notebook}`
        subprocess.call([command],shell=True)
        runpy.run_path(path_name=notebook.with_suffix(".py"))
```

**Comment by christian-oreilly** [comment]
@hanayik @AnthonyAndroulakis I am not sure who has the full rights on that repo, but if it is one of you, could bump my rights a bit? Right now I don't seem to have the right to assign a label to issues. I would have put this one as an enhancement.

**Comment by hanayik** [comment]
@christian-oreilly , I just sent you an invite to be a maintainer. Let me know if you have not received this (check your junk folder too).

**Comment by christian-oreilly** [comment]
Invite received! Thanks @hanayik
