### ISSUE TITLE
load_meshes

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/ipyniivue#33]
bug when calling load_meshes() function. Error thrown due to gl property of niivue not being initialized

will investigate further

(issue brought up through mail)

**Comment by christian-oreilly** [comment]
@cdrake As discussed at the meeting today, this function just sits forever when called on my MacOS system, on VS Code. 

I tried it on a `jupyter notebook` server, and the server spits out:
```
[W 11:20:23.939 NotebookApp] IOPub data rate exceeded.
    The notebook server will temporarily stop sending output
    to the client in order to avoid crashing it.
    To change this limit, set the config variable
    `--NotebookApp.iopub_data_rate_limit`.
    
    Current values:
    NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
    NotebookApp.rate_limit_window=3.0 (secs)
```
That being said, as far as I can tell, it displayed the meshes fine. Maybe the issue this function has in the CI (#38) is related to this error message? I am not sure why the call to this function sits forever in VS code. I looked a bit at some doc (https://code.visualstudio.com/api/extension-guides/notebook) but it would require me more time to digest that doc! Your input would be most welcome.
