### ISSUE TITLE
Some Niivue options do not get properly passed to the Niivue instance

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/ipyniivue#7]
Currently, the Niivue widget (python) can get initialized with a set of options.
On the typescript side, Niivue first gets initialized with 0 inputs, and then the Niivue options are modified after.
Even though `updateGLVolume` is called after each option modification, some options still do not get modified correctly.

**Comment by hanayik** [comment]
@AnthonyAndroulakis , could you give some instructions to replicate this behaviour (maybe using a specific option that is not getting set properly) so that I can test locally on my machine?

**Comment by AnthonyAndroulakis** [comment]
It turns out I was not initializing the Niivue object correctly. I should initialize Niivue with its options rather than initializing with 0 options and then modifying the options.
