### ISSUE TITLE
`pip install` may not work as intended

### ISSUE THREAD

**Issue by arokem** [niivue/ipyniivue#79]
Hello - I am trying to follow the installation instructions in the readme, but something is amiss. After installing with `pip install ipyniivue` in a clean conda env (and after also installing jupyter notebook into the same environment), I try running the [example notebook](https://github.com/niivue/ipyniivue/blob/main/examples/basic_multiplanar.ipynb), but I get the following error on the second cell: 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from ipyniivue import NiiVue, SliceType
      2 # based on https://niivue.github.io/niivue/features/basic.multiplanar.html
      4 volumes = [
      5   { "path": "../images/mni152.nii.gz", "colormap": "gray", "visible": True, "opacity": 1.0 },
      6   { "path": "../images/hippo.nii.gz", "colormap": "red", "visible": True, "opacity": 1 },
      7 
      8 ]

ImportError: cannot import name 'NiiVue' from 'ipyniivue' (/Users/arokem/miniconda3/envs/niivue/lib/python3.10/site-packages/ipyniivue/__init__.py)
```

Are some additional installation steps needed (e.g., with npm)? Thank you!

**Comment by arokem** [comment]
FWIW, when I clone the repo, and run 

`npm run build` 

followed by: 

`pip install -e ".[dev]"` 

the code in that notebook works as expected.

**Comment by kabilar** [comment]
Hi @arokem, I believe that in the `2.0.1` version on [PyPI](https://pypi.org/project/ipyniivue/#history) the module is named `AnyNiivue`.  The latest changes in the repo (that haven't been released to PyPI yet) change the module name to `NiiVue`.  So a workaround would be to use `from ipyniivue import AnyNiivue`.

**Comment by arokem** [comment]
Thank you!
