### ISSUE TITLE
NiivueOptions syntax

### ISSUE THREAD

**Issue by AnthonyAndroulakis** [niivue/ipyniivue#8]
Currently, the NiivueOptions for a Niivue widget can be accessed like so: `nv.text_height`.       
However, this does not exactly mirror the method of accessing an option from a js Niivue object, which is like so: `nv.opts.textHeight`.        

The naming difference (snake case vs camel case) is normal, however, the widget version is missing the "opts." text. 
Ideally, a Niivue widget could have one of its options modified like so:
```py
from ipyniivue import Niivue
nv = Niivue()
nv.opts.text_height = 0.05
```

**Comment by hanayik** [comment]
@AnthonyAndroulakis, one option that we can look into is creating more "setter" and "getter" methods in the core NiiVue project. 

So we could have something like `nv.setTextHeight(newHeight)`, and `nv.getTextHeight()`

**Comment by AnthonyAndroulakis** [comment]
Good idea, this would be helpful.
